name: flutter_hub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  flutter_bloc: ^0.15.0
  url_launcher: ^4.0.3  
  github_repository:
    path: github_repository

  jobs_repository:
    path: jobs_repository

flutter:
  uses-material-design: true